services:
  hdsphere-base:
    build: 
      context: ./hadoop-base
      dockerfile: Dockerfile
    image: hdsphere-base

  hdsphere-master:
    build: 
      context: ./master
      dockerfile: Dockerfile
    image: hdsphere-master
    depends_on:
      - hdsphere-base
  
  hdsphere-pig:
    build: 
      context: ../
      dockerfile: services/pig/Dockerfile
    image: hdsphere-pig
    depends_on:
      - hdsphere-master
  hdsphere-hive:
    build: 
      context: ../
      dockerfile: services/hive/Dockerfile
    image: hdsphere-hive
    depends_on:
      - hdsphere-pig

  hdsphere-spark:
    build: 
      context: ../
      dockerfile: services/spark/Dockerfile
    image: hdsphere-spark
    depends_on:
      - hdsphere-hive

  hdsphere-master-hbase-zookeeper:
    build: 
      context: ../
      dockerfile: services/hbase-zookeeper/master/Dockerfile
    image: hdsphere-master-hbase-zookeeper
    depends_on:
      - hdsphere-spark
  hdsphere-slave:
    build: 
      context: ./slave
      dockerfile: Dockerfile
    image: hdsphere-slave
    depends_on:
      - hdsphere-base

  hdsphere-slave-hbase:
    build: 
      context: ../
      dockerfile: services/hbase-zookeeper/slave/Dockerfile
    image: hdsphere-slave-hbase
    depends_on:
      - hdsphere-slave
    